# This is the config file template filled with example values.
# Copy this file and rename it to config.yml

port: 3500
bind: '127.0.0.1'
reverseProxy: true

dbType: 'sqlite'
dbUrl: 'sqlite:./stream.db'

#dbType: 'mariadb'
#dbUrl: 'mariadb://username:password@host:port/database'

gitlabHost: 'https://gitlab.com'
gitlabClientId: ''
gitlabClientSecret: ''
gitlabGroup: 1234
